version: "3.1"

services:
  datadog-agent:
    container_name: agent
    env_file:
      - datadog.env
    image: "datadog/agent:latest"
    volumes:
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8125:8125/udp"
      - "8126:8126"
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - server.env
    depends_on:
      - datadog-agent
    ports:
      - "8899:8899"
